[package]
name = "kime-engine-backend-latin"
version = "0.1.0"
authors = ["Riey <creeper844@gmail.com>"]
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
kime-engine-backend = { path = "../../backend" }
serde = { version = "1.0.124", features = ["derive"] }
serde_yaml = "0.9"
