[package]
name = "kime-check"
version = "0.1.0"
authors = ["Riey <creeper844@gmail.com>"]
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
owo-colors = "4"
kime-engine-core = { path = "../../engine/core" }
pad = "0.1.6"
serde_yaml = "0.9"
strum = { version = "0.26", features = ["derive"] }
xdg = "2.5"
