[package]
name = "kime-wayland"
description = "Kime Wayland input-method frontend"
version = "0.1.0"
authors = ["Riey <creeper844@gmail.com>"]
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
kime-engine-core = { path = "../../engine/core" }
kime-version = { path = "../../tools/version" }

wayland-client = "0.31"
wayland-protocols = { version = "0.32", features = [
    "client",
    "unstable",
] }
wayland-protocols-misc = { version = "0.3", features = ["client"] }
xkbcommon = { version = "0.9.0", features = ["wayland"] }

libc = "0.2"
log = "0.4"
pico-args = "0.5"
mio = { version = "1.0", features = ["os-ext"] }
timerfd-mio = "0.1"
