[package]
name = "kime-indicator"
description = "Kime system tray indicator showing the current input category"
version = "0.1.0"
authors = ["Riey <creeper844@gmail.com>"]
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
kime-engine-core = { path = "../../engine/core" }
kime-version = { path = "../version" }
kime-run-dir = { path = "../run_dir" }

anyhow = "1.0"
pico-args = "0.5"
log = "0.4"
ksni = "0.3.3"
tokio = { version = "1.49.0", features = ["full"] }
